import streamlit as st
import formatter
import pandas as pd

def render_report(base_data, verify_data):
    i = base_data['inputs']
    r = base_data['results']
    efm = base_data['efm']
    bars = verify_data['rebar_verified']
    
    st.markdown("## 🏗️ Structural Design Calculation Report")
    
    # --- 1. Design Criteria Summary (New!) ---
    st.markdown("### 1. Design Criteria Summary")
    crit_data = {
        "Parameter": ["Design Code", "Method", "Concrete (fc')", "Rebar (fy)", "Superimposed DL", "Live Load"],
        "Value": [
            "ACI 318-19",
            i['method'],
            f"{i['fc_mpa']/0.0980665:.0f} ksc",
            f"{i['fy']:.0f} ksc",
            f"{i['sdl']} kg/m²",
            f"{i['ll']} kg/m²"
        ]
    }
    st.table(pd.DataFrame(crit_data))

    # --- 2. Geometry & Analysis ---
    st.markdown("### 2. Geometry & Analysis Check")
    col1, col2 = st.columns(2)
    with col1:
        st.write(f"**Member Size:** Slab h={r['h']}mm, Col {i['c1']*1000:.0f}x{i['c2']*1000:.0f}mm")
        st.write(f"**Clear Span ($L_n$):** {r['ln']:.2f} m")
        st.write(f"**Design Load ($q_u$):** {r['qu']:.0f} kg/m²")
    with col2:
        pass_flag = r['ratio'] <= 1.0
        st.write(f"**Punching Shear ($V_u$):** {r['vu_kg']/1000:.2f} Tons")
        st.write(f"**Capacity ($\phi V_c$):** {r['phi_vc_kg']/1000:.2f} Tons")
        st.markdown(f"**Status:** :{'green' if pass_flag else 'red'}[{'PASS' if pass_flag else 'FAIL'} (Ratio {r['ratio']:.2f})]")
    
    # --- 3. EFM Verification (If Selected) ---
    if "EFM" in i['method']:
        st.markdown("### 3. EFM Stiffness Verification")
        st.info("Equivalent Frame Properties calculated per ACI 318:")
        st.latex(formatter.fmt_efm_stiffness(efm['Ks'], efm['Sum_Kc'], efm['Kt'], efm['Kec']))
        st.metric("Stiffness Ratio ($\alpha_{ec}$)", f"{efm.get('alpha_ec', 0):.3f}", "Determines Moment Distribution")

    # --- 4. Flexural Design ---
    st.markdown("### 4. Flexural Design & Detailing")
    
    summary_data = []
    for bar in bars:
        summary_data.append({
            "Strip Location": bar['name'],
            "Design Mu (kg-m)": f"{bar['mu']:,.0f}",
            "As Req (cm²)/m": f"{bar['as_target']:.2f}",
            "Selected Rebar": f"DB{bar['user_db']}@{bar['user_spacing']}",
            "As Prov (cm²)/m": f"{bar['as_provided']:.2f}",
            "Status": "✅ PASS" if "SAFE" in bar['status'] else "❌ FAIL"
        })
        
    st.dataframe(pd.DataFrame(summary_data), use_container_width=True)
    
    st.caption("End of Report | Generated by Pro Flat Slab System")
